In [1]:
# # Scikit-learn Introduction

# ## What is Machine Learning?

# Machine Learning (ML) is a branch of Artificial Intelligence (AI) that enables computers to learn patterns from data and make predictions without being explicitly programmed.

# Instead of writing rules manually, we provide data to a machine learning algorithm, which learns the relationship between inputs and outputs.

# ## What is Scikit-learn?

# Scikit-learn (sklearn) is the most popular Machine Learning library in Python.

# It provides simple and efficient tools for:

# - Data Preprocessing
# - Feature Engineering
# - Machine Learning Algorithms
# - Model Evaluation
# - Hyperparameter Tuning
# - Pipelines

# ## Why Learn Scikit-learn?

# - Beginner Friendly
# - Industry Standard
# - Easy API
# - Large Community
# - Used in Data Science and Machine Learning Projects

# ## Applications

# - Sales Prediction
# - House Price Prediction
# - Fraud Detection
# - Spam Email Detection
# - Customer Segmentation
# - Recommendation Systems

# ## What You Will Learn

# - ML Workflow
# - Supervised Learning
# - Unsupervised Learning
# - Scikit-learn Basics
# - First Machine Learning Model

**Code Cell 1
Import Scikit-learn**

In [3]:
import sklearn

print("Scikit-learn Version :", sklearn.__version__)

Scikit-learn Version : 1.9.0

**Code Cell 2
Check Installation**

In [4]:
import numpy as np
import pandas as pd
import sklearn

print("NumPy :", np.__version__)
print("Pandas :", pd.__version__)
print("Scikit-learn :", sklearn.__version__)

NumPy : 2.5.0
Pandas : 3.0.3
Scikit-learn : 1.9.0

In [6]:
# # Machine Learning Types

# ## 1. Supervised Learning

# The model learns from labeled data.

# Examples:

# - House Price Prediction
# - Student Marks Prediction
# - Spam Detection

# Algorithms

# - Linear Regression
# - Logistic Regression
# - Decision Tree
# - Random Forest
# - SVM
# - KNN

# ---

# ## 2. Unsupervised Learning

# The model finds hidden patterns in unlabeled data.

# Examples

# - Customer Segmentation
# - Product Grouping

# Algorithms

# - KMeans
# - PCA

**Code Cell 3
First ML Dataset**

In [7]:
from sklearn.datasets import load_iris

iris = load_iris()

print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>

**Code Cell 4**

In [8]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

**Code Cell 5**

In [9]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

**Code Cell 6**

In [10]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

**Code Cell 7**

In [ ]:
X = iris.data

y = iris.target

print("Features Shape :", X.shape)

print("Target Shape :", y.shape)

# X → Input Features (Independent Variables)
# y → Target (Dependent Variable)

Features Shape : (150, 4)
Target Shape : (150,)

**Code Cell 8
Convert to DataFrame**

In [12]:
df = pd.DataFrame(
    X,
    columns = iris.feature_names
)
df["Species"] = y
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

**Code Cell 9
Target Distribution**

In [13]:
df["Species"].value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

**Code Cell 10
Dataset Information**

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

**Code Cell 11
Statistical Summary**

In [15]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000