In [1]:
# # Linear Regression

# ## What is Linear Regression?

# Linear Regression is one of the simplest and most widely used Machine Learning algorithms.

# It is used to predict a continuous numerical value by finding the relationship between input features (X) and the target variable (y).

# The model learns a straight line called the **Best Fit Line**.

# ## Where is it Used?

# - House Price Prediction
# - Salary Prediction
# - Sales Prediction
# - Stock Price Trend
# - Profit Forecasting

# ## In this Notebook

# - Load Dataset
# - Split Dataset
# - Train Model
# - Make Predictions
# - Evaluate Model
# - Understand Coefficients

**Complete Workflow**

In [26]:
# Collect Data
#       │
#       ▼
# Preprocessing
#       │
#       ▼
# Train-Test Split
#       │
#       ▼
# Create Model
#       │
#       ▼
# fit()
#       │
#       ▼
# predict()
#       │
#       ▼
# Evaluation

Code Cell 1 Import all required libraries.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Code Cell 2
Load Dataset

In [9]:
# We need data to train our Machine Learning model.
# We'll use California Housing Dataset, which comes with Scikit-learn.

housing = fetch_california_housing()
X = pd.DataFrame(
    housing.data,
    columns=housing.feature_names
)

y = housing.target
X.head(100)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
95,2.0096,36.0,2.294016,1.066294,3469.0,1.493328,37.80,-122.26
96,2.8345,31.0,3.894915,1.127966,2048.0,1.735593,37.82,-122.26
97,2.0062,29.0,3.681319,1.175824,202.0,2.219780,37.81,-122.26
98,1.2185,22.0,2.945600,1.016000,2024.0,1.619200,37.82,-122.26
99,2.6104,37.0,3.707143,1.107143,1838.0,1.875510,37.82,-122.26

Code Cell 3
Explore Dataset

In [10]:
print(X.shape)

X.info()

X.describe()

(20640, 8)
<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

Code Cell 4
Split Dataset

In [12]:
# Separate data into training and testing sets.
# The model should learn from one dataset and be evaluated on another.
X_train, X_test, y_train, y_test = train_test_split(

    X,

    y,

    test_size=0.2,

    random_state=42

)

Code Cell 5
Create Model

In [14]:
# Create a Linear Regression object.
# This object contains the algorithm that will learn from the data.
model = LinearRegression()

Code Cell 6 Train the Model

In [15]:
# Teach the model using training data.
# This is where Machine Learning actually happens.

model.fit(

    X_train,

    y_train

)

LinearRegression()

Code Cell 7
Make Predictions

In [18]:
# Predict house prices for unseen test data.
predictions = model.predict(X_test)

predictions[:10]

array([0.71912284, 1.76401657, 2.70965883, 2.83892593, 2.60465725,
       2.01175367, 2.64550005, 2.16875532, 2.74074644, 3.91561473])

Code Cell 8
Compare Actual vs Predicted

In [20]:
comparison = pd.DataFrame({

    "Actual": y_test,

    "Predicted": predictions

})

comparison.head(100)

     Actual  Predicted
0   0.47700   0.719123
1   0.45800   1.764017
2   5.00001   2.709659
3   2.18600   2.838926
4   2.78000   2.604657
..      ...        ...
95  1.15800   1.492405
96  2.78600   2.682587
97  2.50000   1.662020
98  0.85000   1.813387
99  1.77000   2.120443

[100 rows x 2 columns]

Code Cell 9
Model Accuracy

In [21]:
print("MAE :", mean_absolute_error(y_test, predictions))

print("MSE :", mean_squared_error(y_test, predictions))

print("R2 Score :", r2_score(y_test, predictions))

MAE : 0.5332001304956555
MSE : 0.5558915986952442
R2 Score : 0.575787706032451

In [22]:
# Metrics Explained

# MAE (Mean Absolute Error)
# Average prediction error.
# Lower is better.

# MSE (Mean Squared Error)
# Squares the errors before averaging.
# Large mistakes get penalized more.
# Lower is better.

# R² Score 
# Shows how well the model explains the data.
# 1.0 → Perfect
# 0.9 → Excellent
# 0.8 → Good
# 0 → Poor
# Higher is better.

Code Cell 10
Model Coefficients

In [ ]:
coef = pd.DataFrame({

    "Feature": X.columns,

    "Coefficient": model.coef_

})
coef

# Positive coefficient → increases prediction.
# Negative coefficient → decreases prediction.

      Feature  Coefficient
0      MedInc     0.448675
1    HouseAge     0.009724
2    AveRooms    -0.123323
3   AveBedrms     0.783145
4  Population    -0.000002
5    AveOccup    -0.003526
6    Latitude    -0.419792
7   Longitude    -0.433708

Code Cell 11
Intercept

In [ ]:
print(model.intercept_)

# This is the value of c in:
# y = mx + c

-37.02327770606416

Code Cell 12
Predict New House Price

In [25]:
sample = X.iloc[[0]]

prediction = model.predict(sample)

print(prediction)

[4.15194269]