In [2]:
# # End-to-End Sales Machine Learning Project

# ## Project Objective

# In this project, we will build a complete Machine Learning workflow using the Sales Dataset.

# Instead of learning concepts separately, we will apply them in a real-world project.

# ## What We Will Cover

# - Load Dataset
# - Explore Data
# - Data Cleaning
# - Feature Engineering
# - Exploratory Data Analysis (EDA)
# - Data Preprocessing
# - Train-Test Split
# - Model Training
# - Model Evaluation
# - Hyperparameter Tuning
# - Model Saving
# - Prediction

# ## Libraries Used

# - Pandas
# - NumPy
# - Matplotlib
# - Plotly
# - Scikit-learn
# - Joblib

# ## Goal

# Predict whether a sales transaction is High Profit or Low Profit using Machine Learning.

In [3]:
# # Step 1 : Import Dataset

# In this step, we will load the Sales Dataset into Pandas.

# After loading, we will inspect the dataset before performing any preprocessing.

# Remember:

# Never start building a Machine Learning model without understanding the dataset first.

In [6]:
import pandas as pd

df = pd.read_csv("../datasets/raw/sales.csv")

df.head(10)

,Order_ID,Order_Date,Ship_Date,Customer_ID,Customer_Name,Gender,Age,Email,Phone,Region,...,Discount,Sales,Cost,Profit,Payment_Mode,Order_Priority,Customer_Segment,Delivery_Days,Customer_Rating,Returned
0,ORD000004,03-07-2022,06-07-2022,CUST00945,Logan Khosla,Male,19,uppaltarak@example.net,1.050097e+09,West,...,30.0,193235.7,213311.48,-20075.78,Cash,Medium,Corporate,3,4.0,No
1,ORD000005,20-03-2023,21-03-2023,CUST00560,Tamanna Halder,Female,53,hemal72@example.net,1.918315e+08,North,...,15.0,243780.0,218272.56,25507.44,Cash,High,Regular,1,1.0,Yes
2,ORD000006,01-09-2024,04-09-2024,CUST02577,Noah Sem,Male,20,imaranben@example.org,8.319264e+09,North,...,15.0,69628.6,69590.62,37.98,Credit Card,High,Regular,3,4.0,No
3,ORD000007,23-01-2024,25-01-2024,CUST01069,Onkar Edwin,Male,51,xhalder@example.org,9.195530e+11,North,...,20.0,89200.0,90045.00,-845.00,Net Banking,Medium,Corporate,2,1.0,Yes
4,ORD000008,13-07-2022,14-07-2022,CUST03566,Nachiket Prabhakar,Male,25,ichand@example.net,8.035514e+09,North,...,15.0,137098.2,135832.23,1265.97,Cash,Critical,Regular,1,2.0,Yes
5,ORD000009,07-10-2025,12-10-2025,CUST03351,Zansi Jaggi,Female,23,raghavannachiket@example.org,8.725925e+09,South,...,0.0,146965.0,100636.15,46328.85,Credit Card,Critical,Regular,5,2.0,Yes
6,ORD000010,05-03-2024,09-03-2024,CUST00349,Lakshmi Ahuja,Female,25,lipika50@example.org,9.193040e+11,South,...,0.0,351610.0,274168.00,77442.00,Cash,Low,Regular,4,4.0,No
7,ORD000011,31-07-2025,06-08-2025,CUST00547,Harinakshi Chakraborty,Female,27,qlala@example.com,2.506909e+09,East,...,20.0,42252.8,39490.24,2762.56,Debit Card,High,Regular,6,1.0,Yes
8,ORD000012,09-08-2023,13-08-2023,CUST01834,Maanav Narain,Male,18,ekbalpatla@example.com,9.101990e+11,West,...,30.0,610082.2,717969.46,-107887.26,Cash,Medium,Corporate,4,3.0,No
9,ORD000013,08-07-2025,10-07-2025,CUST00001,Saumya Dhaliwal,Female,43,divyasaha@example.net,3.151616e+09,West,...,5.0,103626.0,60805.10,42820.90,UPI,Critical,Premium,2,4.0,Yes

In [7]:
# # Step 2 : Understand the Dataset

# Before cleaning or training a model, we need to answer:

# - How many rows are there?
# - How many columns are there?
# - Which columns are numerical?
# - Which columns are categorical?
# - Are there missing values?

# This helps us decide the preprocessing steps.

In [8]:
df.shape

(10100, 28)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10100 non-null  str
 1   Order_Date        10100 non-null  str
 2   Ship_Date         10100 non-null  str
 3   Customer_ID       10100 non-null  str
 4   Customer_Name     10100 non-null  str
 5   Gender            10100 non-null  str
 6   Age               10100 non-null  int64
 7   Email             9899 non-null   str
 8   Phone             9899 non-null   float64
 9   Region            10100 non-null  str
 10  State             10100 non-null  str
 11  City              10100 non-null  str
 12  Product_ID        10100 non-null  str
 13  Product_Name      10100 non-null  str
 14  Category          10100 non-null  str
 15  Brand             10100 non-null  str
 16  Quantity          10100 non-null  int64
 17  Unit_Price        10100 non-null  int64
 18  Discount          9899 non-null   float64
 19  Sales             10100 non-null  float64
 20  Cost              10100 non-null  float64
 21  Profit            10100 non-null  float64
 22  Payment_Mode      10100 non-null  str
 23  Order_Priority    10100 non-null  str
 24  Customer_Segment  10100 non-null  str
 25  Delivery_Days     10100 non-null  int64
 26  Customer_Rating   9899 non-null   float64
 27  Returned          10100 non-null  str
dtypes: float64(6), int64(4), str(18)
memory usage: 2.2 MB

In [14]:
df.describe()

,Age,Phone,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Delivery_Days,Customer_Rating
count,10100.000000,9.899000e+03,10100.000000,10100.000000,9899.000000,1.010000e+04,1.010000e+04,1.010000e+04,10100.000000,9899.000000
mean,43.600891,3.039694e+11,5.901386,49683.125644,10.855642,2.603043e+05,2.046550e+05,4.734208e+04,3.988713,2.996969
std,15.613399,4.274280e+11,5.559638,28959.543051,8.556993,3.885400e+05,2.578058e+05,9.603972e+04,1.662858,1.416637
min,-1.000000,2.333563e+06,1.000000,1351.000000,0.000000,1.148350e+03,8.238100e+02,-2.296132e+05,1.000000,1.000000
25%,30.000000,3.715469e+09,2.000000,25390.000000,5.000000,5.917590e+04,4.329150e+04,7.661935e+03,3.000000,2.000000
50%,44.000000,7.469739e+09,3.000000,50172.000000,10.000000,1.398900e+05,1.054706e+05,2.297298e+04,4.000000,3.000000
75%,57.000000,9.123640e+11,9.000000,73012.000000,15.000000,3.017790e+05,2.408620e+05,5.569008e+04,5.000000,4.000000
max,70.000000,9.199940e+11,20.000000,99271.000000,30.000000,9.400326e+06,1.605747e+06,2.970588e+06,7.000000,5.000000

In [15]:
df.sample(5)

,Order_ID,Order_Date,Ship_Date,Customer_ID,Customer_Name,Gender,Age,Email,Phone,Region,...,Discount,Sales,Cost,Profit,Payment_Mode,Order_Priority,Customer_Segment,Delivery_Days,Customer_Rating,Returned
9356,ORD009360,28-10-2025,31-10-2025,CUST00697,Mitesh Luthra,Male,40,kurianzehaan@example.com,4.394556e+09,South,...,0.0,29742.0,17721.84,12020.16,Debit Card,Low,Regular,3,1.0,Yes
3640,ORD003644,12-02-2022,18-02-2022,CUST01921,Samuel Wagle,Male,66,fsundaram@example.net,3.787498e+09,Central,...,5.0,514179.9,343999.80,170180.10,UPI,Low,Corporate,6,4.0,No
4597,ORD004601,03-03-2022,06-03-2022,CUST01425,Jason Chatterjee,Male,67,chanderzayan@example.net,8.778698e+09,South,...,10.0,17616.6,13784.92,3831.68,Debit Card,Medium,Premium,3,2.0,Yes
7838,ORD007842,09-10-2025,13-10-2025,CUST02989,Anya Magar,Female,63,sahotavarsha@example.net,3.066614e+09,South,...,15.0,786103.8,640939.56,145164.24,UPI,Low,Corporate,4,4.0,Yes
6069,ORD006073,21-10-2024,26-10-2024,CUST03210,Omkaar Nayar,Male,69,jkhatri@example.net,4.476907e+09,Central,...,5.0,137016.6,117346.29,19670.31,Debit Card,Low,Premium,5,1.0,Yes

In [16]:
# # Why are we exploring the dataset?

# Before applying Machine Learning, we must understand the data.

# This helps us identify:

# - Missing Values
# - Wrong Data Types
# - Duplicate Records
# - Outliers
# - Useful Features

# Good data understanding leads to better models.

In [17]:
df.columns

Index(['Order_ID', 'Order_Date', 'Ship_Date', 'Customer_ID', 'Customer_Name',
       'Gender', 'Age', 'Email', 'Phone', 'Region', 'State', 'City',
       'Product_ID', 'Product_Name', 'Category', 'Brand', 'Quantity',
       'Unit_Price', 'Discount', 'Sales', 'Cost', 'Profit', 'Payment_Mode',
       'Order_Priority', 'Customer_Segment', 'Delivery_Days',
       'Customer_Rating', 'Returned'],
      dtype='str')

In [18]:
df.dtypes

Order_ID                str
Order_Date              str
Ship_Date               str
Customer_ID             str
Customer_Name           str
Gender                  str
Age                   int64
Email                   str
Phone               float64
Region                  str
State                   str
City                    str
Product_ID              str
Product_Name            str
Category                str
Brand                   str
Quantity              int64
Unit_Price            int64
Discount            float64
Sales               float64
Cost                float64
Profit              float64
Payment_Mode            str
Order_Priority          str
Customer_Segment        str
Delivery_Days         int64
Customer_Rating     float64
Returned                str
dtype: object

In [19]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Ship_Date             0
Customer_ID           0
Customer_Name         0
Gender                0
Age                   0
Email               201
Phone               201
Region                0
State                 0
City                  0
Product_ID            0
Product_Name          0
Category              0
Brand                 0
Quantity              0
Unit_Price            0
Discount            201
Sales                 0
Cost                  0
Profit                0
Payment_Mode          0
Order_Priority        0
Customer_Segment      0
Delivery_Days         0
Customer_Rating     201
Returned              0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(98)

In [21]:
df.nunique()

Order_ID            10000
Order_Date           1461
Ship_Date            1460
Customer_ID          3673
Customer_Name        3640
Gender                  2
Age                    54
Email                3651
Phone                3589
Region                  5
State                  18
City                   90
Product_ID            150
Product_Name           50
Category                5
Brand                  20
Quantity               20
Unit_Price            150
Discount                7
Sales                5505
Cost                 2435
Profit               5727
Payment_Mode            5
Order_Priority          4
Customer_Segment        3
Delivery_Days           7
Customer_Rating         5
Returned                2
dtype: int64

Abhi tak humne kya kiya?

In [22]:
# Sales Dataset

# ↓

# Load Dataset

# ↓

# Understand Dataset

# ↓

# Shape

# ↓

# Info

# ↓

# Statistics

# ↓

# Missing Values

# ↓

# Duplicate Values

# ↓

# Unique Values