In [2]:
# # Plotly Heatmaps

# ## What is a Heatmap?

# A Heatmap is a graphical representation of data where values are represented by colors.

# It helps us quickly identify patterns, relationships, and correlations.

# ## Why do we use Heatmaps?

# - Find correlation between numerical columns
# - Detect strong positive/negative relationships
# - Feature Selection for Machine Learning
# - Business Data Analysis

# ## Real World Examples

# - Sales Correlation
# - Student Performance
# - Stock Market Analysis
# - Customer Behavior
# - Machine Learning Feature Selection

# ## What You Will Learn

# - Correlation Matrix
# - Correlation Heatmap
# - Color Scale
# - Text Values
# - Business Example

**Code Cell 1**

In [3]:
# ============================================================
# Import Libraries
# ============================================================

import pandas as pd
import plotly.express as px

df = pd.read_csv("../datasets/raw/sales.csv")

df.head()

,Order_ID,Order_Date,Ship_Date,Customer_ID,Customer_Name,Gender,Age,Email,Phone,Region,...,Discount,Sales,Cost,Profit,Payment_Mode,Order_Priority,Customer_Segment,Delivery_Days,Customer_Rating,Returned
0,ORD000004,03-07-2022,06-07-2022,CUST00945,Logan Khosla,Male,19,uppaltarak@example.net,1.050097e+09,West,...,30.0,193235.7,213311.48,-20075.78,Cash,Medium,Corporate,3,4.0,No
1,ORD000005,20-03-2023,21-03-2023,CUST00560,Tamanna Halder,Female,53,hemal72@example.net,1.918315e+08,North,...,15.0,243780.0,218272.56,25507.44,Cash,High,Regular,1,1.0,Yes
2,ORD000006,01-09-2024,04-09-2024,CUST02577,Noah Sem,Male,20,imaranben@example.org,8.319264e+09,North,...,15.0,69628.6,69590.62,37.98,Credit Card,High,Regular,3,4.0,No
3,ORD000007,23-01-2024,25-01-2024,CUST01069,Onkar Edwin,Male,51,xhalder@example.org,9.195530e+11,North,...,20.0,89200.0,90045.00,-845.00,Net Banking,Medium,Corporate,2,1.0,Yes
4,ORD000008,13-07-2022,14-07-2022,CUST03566,Nachiket Prabhakar,Male,25,ichand@example.net,8.035514e+09,North,...,15.0,137098.2,135832.23,1265.97,Cash,Critical,Regular,1,2.0,Yes

**Code Cell 2
Select Numerical Columns**

In [4]:
numeric_df = df.select_dtypes(include="number")

numeric_df.head()

,Age,Phone,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Delivery_Days,Customer_Rating
0,19,1.050097e+09,19,14529,30.0,193235.7,213311.48,-20075.78,3,4.0
1,53,1.918315e+08,4,71700,15.0,243780.0,218272.56,25507.44,1,1.0
2,20,8.319264e+09,1,81916,15.0,69628.6,69590.62,37.98,3,4.0
3,51,9.195530e+11,20,5575,20.0,89200.0,90045.00,-845.00,2,1.0
4,25,8.035514e+09,3,53764,15.0,137098.2,135832.23,1265.97,1,2.0

**Code Cell 3
Correlation Matrix**

In [5]:
corr = numeric_df.corr()

corr

,Age,Phone,Quantity,Unit_Price,Discount,Sales,Cost,Profit,Delivery_Days,Customer_Rating
Age,1.000000,0.035353,0.004882,-0.013951,-0.005853,-0.005115,0.003466,-0.012335,-0.000578,-0.016093
Phone,0.035353,1.000000,0.003040,0.003366,0.005505,-0.001128,0.013315,-0.006502,0.014784,0.003345
Quantity,0.004882,0.003040,1.000000,-0.004648,0.482424,0.609894,0.750497,0.358017,0.013193,0.021009
Unit_Price,-0.013951,0.003366,-0.004648,1.000000,-0.002257,0.390394,0.462135,0.273643,-0.015894,-0.001104
Discount,-0.005853,0.005505,0.482424,-0.002257,1.000000,0.230634,0.360955,-0.084733,0.016665,0.009298
Sales,-0.005115,-0.001128,0.609894,0.390394,0.230634,1.000000,0.794534,0.742304,-0.014127,0.010491
Cost,0.003466,0.013315,0.750497,0.462135,0.360955,0.794534,1.000000,0.403155,-0.007557,0.015068
Profit,-0.012335,-0.006502,0.358017,0.273643,-0.084733,0.742304,0.403155,1.000000,-0.019436,-0.003299
Delivery_Days,-0.000578,0.014784,0.013193,-0.015894,0.016665,-0.014127,-0.007557,-0.019436,1.000000,0.002519
Customer_Rating,-0.016093,0.003345,0.021009,-0.001104,0.009298,0.010491,0.015068,-0.003299,0.002519,1.000000

**Code Cell 4
Basic Heatmap**

In [ ]:
fig = px.imshow(
    corr,
    text_auto=True, # values ko cells ke andar show karta hai.
    title="Correlation Heatmap"
)
fig.show()

**Code Cell 5
Heatmap with Color Scale**

In [7]:
fig = px.imshow(

    corr,

    text_auto=True,

    color_continuous_scale="RdBu",

    title="Correlation Heatmap"

)

fig.show()

**Code Cell 6
Viridis Color Scale**

In [8]:
fig = px.imshow(

    corr,

    color_continuous_scale="Viridis",

    text_auto=True

)

fig.show()

**Code Cell 7
Plasma Color Scale**

In [9]:
fig = px.imshow(

    corr,

    color_continuous_scale="Plasma",

    text_auto=True

)

fig.show()

**Code Cell 8
Business Example**

In [12]:
important_columns = df[

    [

        "Sales",

        "Profit",

        "Quantity",

        "Discount",

    ]

]

corr = important_columns.corr()

fig = px.imshow(

    corr,

    text_auto=True,

    color_continuous_scale="RdBu",

    title="Business Correlation"

)

fig.show()

**Important Syntax**

In [13]:
# corr = df.select_dtypes(include="number").corr()

# fig = px.imshow(

#     corr,

#     text_auto=True,

#     color_continuous_scale="RdBu"

# )

# fig.show()